// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221011152454_Mig11")]
    partial class Mig11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entity.Concrete.Adres", b =>
                {
                    b.Property<int>("adresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("adresId"), 1L, 1);

                    b.Property<string>("adress")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("adresId");

                    b.HasIndex("userId");

                    b.ToTable("Adresses");

                    b.HasData(
                        new
                        {
                            adresId = 1,
                            adress = "Cemal Sururi Sokak Mecidiyekoy/Sisli/Istanbul",
                            name = "Ev",
                            userId = 1
                        },
                        new
                        {
                            adresId = 2,
                            adress = "Bilmemne Sokak Bostancı/Kadıkoy/Istanbul",
                            name = "Is",
                            userId = 1
                        },
                        new
                        {
                            adresId = 3,
                            adress = "Cemal Sururi Sokak Mecidiyekoy/Sisli/Istanbul",
                            name = "Ev",
                            userId = 2
                        });
                });

            modelBuilder.Entity("Entity.Concrete.PaymentCard", b =>
                {
                    b.Property<int>("paymentCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymentCardId"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("paymentCardId");

                    b.HasIndex("userId");

                    b.ToTable("PaymentCards");

                    b.HasData(
                        new
                        {
                            paymentCardId = 1,
                            name = "Akbank",
                            userId = 1
                        },
                        new
                        {
                            paymentCardId = 2,
                            name = "Vakıfbank",
                            userId = 2
                        });
                });

            modelBuilder.Entity("Entity.Concrete.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"), 1L, 1);

                    b.Property<string>("birthDate")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("eMail")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("gender")
                        .HasColumnType("bit");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("nickName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("passWord")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            birthDate = "30-12-1992",
                            eMail = "samet66@gmail.com",
                            fullName = "Abdussamet Solak",
                            gender = true,
                            imageUrl = "https://i0.wp.com/www.thewhitetree.org/wp-content/uploads/2015/11/Thorin.jpg",
                            nickName = "Samet",
                            passWord = "123",
                            phoneNumber = "123"
                        },
                        new
                        {
                            userId = 2,
                            birthDate = "30-12-1994",
                            eMail = "elif@gmail.com",
                            fullName = "Elif Solak",
                            gender = false,
                            imageUrl = "https://cdn.yeniakit.com.tr/images/news/625/cate-blanchett-b2b56d.jpg",
                            nickName = "Elif",
                            passWord = "123",
                            phoneNumber = "123"
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Adres", b =>
                {
                    b.HasOne("Entity.Concrete.User", "User")
                        .WithMany("Adresses")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Concrete.PaymentCard", b =>
                {
                    b.HasOne("Entity.Concrete.User", "User")
                        .WithMany("PaymentCards")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Concrete.User", b =>
                {
                    b.Navigation("Adresses");

                    b.Navigation("PaymentCards");
                });
#pragma warning restore 612, 618
        }
    }
}
